### ISSUE TITLE
AnimManager buffer size is decreased for 16x16

### ISSUE THREAD

**Issue by pclewis** [pclewis/mcpatcher#2]
Causes crash in some situations?

java.nio.BufferOverflowException
at java.nio.DirectByteBuffer.put(Unknown Source)
at java.nio.ByteBuffer.put(Unknown Source)
at ey.a(SourceFile:135)
at ey.a(SourceFile:53)
at bq.a(SourceFile:69)
at iq.c(SourceFile:355)
at iq.b(SourceFile:284)
at net.minecraft.client.Minecraft.run(SourceFile:608)
at java.lang.Thread.run(Unknown Source)

**Comment by pclewis** [comment]
fixed
