### ISSUE TITLE
Closing mod filelist window breaks filestream?

### ISSUE THREAD

**Issue by BloodyRain2k** [pclewis/mcpatcher#40]
I noticed that if you close the filelist window of a mod with either cancel or the x it seems to break the filestream because patching after that always results in an error when that mod is about to get patched in.
A restart of MCP fixes that so the mod's not broken.

java.lang.IllegalStateException: zip file closed
    at java.util.zip.ZipFile.ensureOpen(Unknown Source)
    at java.util.zip.ZipFile.getInputStream(Unknown Source)
    at com.pclewis.mcpatcher.ExternalMod.openFile(ExternalMod.java:35)
    at com.pclewis.mcpatcher.MCPatcher.addFile(MCPatcher.java:594)
    at com.pclewis.mcpatcher.MCPatcher.applyMods(MCPatcher.java:586)
    at com.pclewis.mcpatcher.MCPatcher.patch(MCPatcher.java:474)
    at com.pclewis.mcpatcher.MainForm$11$PatchThread.run(MainForm.java:350)
    at java.lang.Thread.run(Unknown Source)

Restoring original minecraft.jar due to previous error

**Comment by prupe** [comment]
Good catch!  Fixed in 2.3.0.
