### ISSUE TITLE
Conflicts with MCForge

### ISSUE THREAD

**Issue by LordXaosa** [pclewis/mcpatcher#46]
[spoiler][code]
MCPatcher version is 2.3.6_02
OS: Windows Server 2008 R2 6.1 amd64
JVM: Oracle Corporation 1.8.0-ea (64 bit)
Classpath: C:\Users\Administrator\Downloads\minecraft\mcpatcher-2.3.6_02.exe
Exception in thread "main" java.lang.SecurityException: SHA1 digest error for net/minecraft/client/Minecraft.class
    at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at javassist.bytecode.AttributeInfo.<init>(AttributeInfo.java:69)
    at javassist.bytecode.SourceFileAttribute.<init>(SourceFileAttribute.java:35)
    at javassist.bytecode.AttributeInfo.read(AttributeInfo.java:113)
    at javassist.bytecode.ClassFile.read(ClassFile.java:798)
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
    at com.pclewis.mcpatcher.MinecraftJar$Info.extractVersion(MinecraftJar.java:375)
    at com.pclewis.mcpatcher.MinecraftJar$Info.initialize(MinecraftJar.java:318)
    at com.pclewis.mcpatcher.MinecraftJar$Info.<init>(MinecraftJar.java:284)
    at com.pclewis.mcpatcher.MinecraftJar.<init>(MinecraftJar.java:24)
    at com.pclewis.mcpatcher.MCPatcher.setMinecraft(MCPatcher.java:165)
    at com.pclewis.mcpatcher.UserInterface.go(UserInterface.java:51)
    at com.pclewis.mcpatcher.MCPatcher.main(MCPatcher.java:135)

Unexpected error while handling UI event java.awt.event.MouseEvent[MOUSE_RELEASED,(468,82),absolute(848,303),button=1,modifiers=Button1,clickCount=1] on frame0
java.lang.SecurityException: SHA1 digest error for net/minecraft/client/Minecraft.class
    at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at java.io.DataInputStream.readFully(Unknown Source)
    at javassist.bytecode.AttributeInfo.<init>(AttributeInfo.java:69)
    at javassist.bytecode.SourceFileAttribute.<init>(SourceFileAttribute.java:35)
    at javassist.bytecode.AttributeInfo.read(AttributeInfo.java:113)
    at javassist.bytecode.ClassFile.read(ClassFile.java:798)
    at javassist.bytecode.ClassFile.<init>(ClassFile.java:114)
    at com.pclewis.mcpatcher.MinecraftJar$Info.extractVersion(MinecraftJar.java:375)
    at com.pclewis.mcpatcher.MinecraftJar$Info.initialize(MinecraftJar.java:318)
    at com.pclewis.mcpatcher.MinecraftJar$Info.<init>(MinecraftJar.java:284)
    at com.pclewis.mcpatcher.MinecraftJar.<init>(MinecraftJar.java:24)
    at com.pclewis.mcpatcher.MCPatcher.setMinecraft(MCPatcher.java:165)
    at com.pclewis.mcpatcher.MainForm$4.actionPerformed(MainForm.java:183)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at com.pclewis.mcpatcher.MainForm$1.dispatchEvent(MainForm.java:92)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
[/code][/spoiler]

**Comment by prupe** [comment]
Exception in thread "main" java.lang.SecurityException: SHA1 digest error for net/minecraft/client/Minecraft.class
at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)

Looks like you didn't delete META-INF when you installed forge.

**Comment by LordXaosa** [comment]
No, it has been deleted...
