### ISSUE TITLE
Crash by ModLoader

### ISSUE THREAD

**Issue by z2s8** [pclewis/mcpatcher#53]
***************************************_BEGIN**_*****************************************************************
      Minecraft has crashed!  
      ----------------------      

Minecraft has stopped running because it encountered a problem; Exception occured in ModLoader
This error has been saved to /home/user/.minecraft/crash-reports/crash-2012-08-21_11.23.00-client.txt for your convenience. Please include a copy of this file if you report this crash to anyone.

--- BEGIN ERROR REPORT 25228580 --------
Generated 2012.08.21. 11:23
- Minecraft Version: 1.3.2
- Operating System: Linux (i386) version 3.0.0-24-generic
- Java Version: 1.6.0_24, Sun Microsystems Inc.
- Java VM Version: OpenJDK Client VM (mixed mode, sharing), Sun Microsystems Inc.
- Memory: 5379480 bytes (5 MB) / 36614144 bytes (34 MB) up to 1037959168 bytes (989 MB)
- JVM Flags: 1 total; -Xmx1024m
- ModLoader: Mods loaded: 1
  ModLoader 1.3.2

java.lang.NoClassDefFoundError: wecui/InitializationFactory
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2308)
    at java.lang.Class.getDeclaredFields(Class.java:1760)
    at ModLoader.setupProperties(ModLoader.java:2064)
    at ModLoader.addMod(ModLoader.java:342)
    at ModLoader.readFromClassPath(ModLoader.java:1333)
    at ModLoader.init(ModLoader.java:931)
    at ModLoader.addAllRenderers(ModLoader.java:185)
    at avy.<init>(RenderManager.java:87)
    at avy.<clinit>(RenderManager.java:14)
    at net.minecraft.client.Minecraft.a(SourceFile:260)
    at net.minecraft.client.Minecraft.run(SourceFile:516)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.ClassNotFoundException: wecui.InitializationFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 23 more
--- END ERROR REPORT e2cd8158 ----------
******************************************************************_END**_******************************************************
Hi I just patched minecraft first with mcatcher for hd texture fix, then i installed modloader 1.3.2, then installed wecui 1.3.1. When i started mc, it displayed the mojang logo than crashed every time. I am using ubuntu 11.10 32-bit, I have about 3 GB of RAM and I don't know why it is crashing when I start. Please help !!! Thanks.

**Comment by prupe** [comment]
wecui is only for 1.3.1 not 1.3.2, correct?

**Comment by z2s8** [comment]
yes, but the author of wecui say's it is working on 3.1.2 too
